name = "cf-worker-signal"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-27"

kv_namespaces = [
    { binding = "kv_cf_worker_signal", id = "" },
]

[build]
command = "cargo install -q worker-build && worker-build --release"
